config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :jobs do
    member do
      post :follow
      post :unfollow
    end
    collection do
      get :search
    end
    resources :resumes
  end

  root "welcome#index"

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end

      resources :resumes
    end
  end

  namespace :account do
    resources :jobs
    resources :resumes
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id               :integer          not null, primary key
#  title            :string
#  description      :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  wage_upper_bound :integer
#  wage_lower_bound :integer
#  contact_email    :string
#  is_hidden        :boolean          default("t")
#  user_id          :integer
#  location         :string
#  category         :string
#  company          :string
#

class Job < ApplicationRecord
  validates :title, presence: { message: "请填写职位名称" }
  validates :wage_upper_bound, presence: { message: "请填写薪资上限" }
  validates :wage_lower_bound, presence: { message: "请填写薪资下限" }
  validates :wage_lower_bound, numericality: { greater_than: 0, message: "薪资下限必须大于零" }
  validates :wage_lower_bound, numericality: { less_than: :wage_upper_bound, message: "薪资下限不能高于薪资上限" }
  validates :location, presence: { message: "请选择工作地点" }
  validates :category, presence: { message: "请选择工作种类" }
  validates :contact_email, presence: { message: "请填写联系用邮箱" }
  validates_format_of :contact_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i , message: "请输入正确的邮箱格式"


  scope :published, -> {where(is_hidden: false)}
  scope :recent, -> {order('created_at DESC')}

  has_many :resumes
  belongs_to :user
  has_many :favorites
  has_many :followers, through: :favorites, source: :user
  has_many :applicant, through: :resumes, source: :user
end

app/controllers/account/jobs_controller.rb
class Account::JobsController < ApplicationController
  before_action :authenticate_user!

  def index
    @jobs = case params[:order]
    when 'by_lower_bound'
      current_user.favorited_jobs.order('wage_lower_bound DESC').paginate(:page => params[:page], :per_page => 5)
    when 'by_upper_bound'
      current_user.favorited_jobs.order('wage_upper_bound DESC').paginate(:page => params[:page], :per_page => 5)
    else
      current_user.favorited_jobs.recent.paginate(:page => params[:page], :per_page => 5)
    end
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_is_admin

  layout "admin"

  def index
    @jobs = current_user.jobs.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @job = Job.new
    render :layout => false
  end

  def show
    find_job_and_check_permission
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    @job.company = current_user.name

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    find_job_and_check_permission
  end

  def update
    find_job_and_check_permission
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    find_job_and_check_permission
    @job.destroy
    redirect_to admin_jobs_path, alert: "已删除工作！"
  end

  def publish
    find_job_and_check_permission
    @job.is_hidden = false
    @job.save
    redirect_to :back
  end

  def hide
    find_job_and_check_permission
    @job.is_hidden = true
    @job.save
    redirect_to :back
  end

  private

  def find_job_and_check_permission
    @job = Job.find(params[:id])

    if current_user != @job.user
      redirect_to root_path, alert: "你没有权限！"
    end
  end

  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden, :category, :location, :company)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :follow, :unfollow]
  before_action :validate_search_key, only: [:search]


  def index
    if params[:location].present?
      @location = params[:location]
      @jobs = case params[:order]
      when 'by_lower_bound'
        Job.where(:is_hidden => false, :location => @location).order('wage_lower_bound DESC').paginate(:page => params[:page], :per_page => 10)
      when 'by_upper_bound'
        Job.where(:is_hidden => false, :location => @location).order('wage_upper_bound DESC').paginate(:page => params[:page], :per_page => 10)
      else
        Job.where(:is_hidden => false, :location => @location).recent.paginate(:page => params[:page], :per_page => 10)
      end

    elsif params[:category].present?
      @category = params[:category]
      @jobs = case params[:order]
      when 'by_lower_bound'
        Job.where(:is_hidden => false, :category => @category).order('wage_lower_bound DESC').paginate(:page => params[:page], :per_page => 10)
      when 'by_upper_bound'
        Job.where(:is_hidden => false, :category => @category).order('wage_upper_bound DESC').paginate(:page => params[:page], :per_page => 10)
      else
        Job.where(:is_hidden => false, :category => @category).recent.paginate(:page => params[:page], :per_page => 10)
      end

    else
      @jobs = case params[:order]
      when 'by_lower_bound'
        Job.published.order('wage_lower_bound DESC').paginate(:page => params[:page], :per_page => 10)
      when 'by_upper_bound'
        Job.published.order('wage_upper_bound DESC').paginate(:page => params[:page], :per_page => 10)
      else
        Job.published.recent.paginate(:page => params[:page], :per_page => 10)
      end
    end
  end

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "该工作暂未公开"
      redirect_to root_path
    end
  end

  def follow
    @job = Job.find(params[:id])

    if !current_user.is_follower_of?(@job)
      current_user.follow!(@job)
      flash[:notice] = "已收藏工作"
    end

    redirect_to :back
  end

  def unfollow
    @job = Job.find(params[:id])

    if current_user.is_follower_of?(@job)
      current_user.unfollow!(@job)
      flash[:alert] = "收藏已取消"
    end

    redirect_to :back
  end

  def search
    if @query_string.present?
      search_result = Job.published.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.recent.paginate(:page => params[:page], :per_page => 10 )
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "")
    if params[:q].present?
      @search_criteria =  search_criteria(@query_string)
    end
  end

  def search_criteria(query_string)
    { :title_or_description_or_location_or_category_or_company_cont => query_string }
  end
end

app/helpers/account/jobs_helper.rb
module Account::JobsHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_bar.html.erb
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <td>职位名称</td>
      <td>薪资范围</td>
      <td>职位类别</td>
      <td>发布公司</td>
      <td>城市</td>
      <td>发布时间</td>
    </tr>
  </thead>
  <tbody>
    <% @jobs = Job.where(:is_hidden => false, :category => "酒吧").recent.paginate(:page => params[:page], :per_page => 10) %>
    <% @jobs.each do |job| %>
    <tr>
      <td>
        <%= link_to(job.title, job_path(job)) %>
      </td>
      <td>
        <%= job.wage_lower_bound %> ～ <%= job.wage_upper_bound %>
      </td>
      <td>
        <%= job.category %>
      </td>
      <td>
        <%= job.company %>
      </td>
      <td>
        <%= job.location %>
      </td>
      <td>
        <%= job.created_at %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= will_paginate @jobs %>
</div>

app/views/jobs/_coffee.html.erb
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <td>职位名称</td>
      <td>薪资范围</td>
      <td>职位类别</td>
      <td>发布公司</td>
      <td>城市</td>
      <td>发布时间</td>
    </tr>
  </thead>
  <tbody>
    <% @jobs = Job.where(:is_hidden => false, :category => "咖啡").recent.paginate(:page => params[:page], :per_page => 10) %>
    <% @jobs.each do |job| %>
    <tr>
      <td>
        <%= link_to(job.title, job_path(job)) %>
      </td>
      <td>
        <%= job.wage_lower_bound %> ～ <%= job.wage_upper_bound %>
      </td>
      <td>
        <%= job.category %>
      </td>
      <td>
        <%= job.company %>
      </td>
      <td>
        <%= job.location %>
      </td>
      <td>
        <%= job.created_at %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= will_paginate @jobs %>
</div>

app/views/jobs/_restaurant.html.erb
<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <td>职位名称</td>
      <td>薪资范围</td>
      <td>职位类别</td>
      <td>发布公司</td>
      <td>城市</td>
      <td>发布时间</td>
    </tr>
  </thead>
  <tbody>
    <% @jobs = Job.where(:is_hidden => false, :category => "餐厅").recent.paginate(:page => params[:page], :per_page => 10) %>
    <% @jobs.each do |job| %>
    <tr>
      <td>
        <%= link_to(job.title, job_path(job)) %>
      </td>
      <td>
        <%= job.wage_lower_bound %> ～ <%= job.wage_upper_bound %>
      </td>
      <td>
        <%= job.category %>
      </td>
      <td>
        <%= job.company %>
      </td>
      <td>
        <%= job.location %>
      </td>
      <td>
        <%= job.created_at %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= will_paginate @jobs %>
</div>

app/views/jobs/_search_bar.html.erb
<%= form_tag search_jobs_path , :method => :get, :class => "jobs-search-form" do %>
  <div class="input-group">
    <input type="text" class="form-control search-bar-input" name="q" value="<%= params[:q] %>" placeholder="搜索工作名称、地点、公司名">

    <span class="input-group-btn">
      <button type="submit" class="btn btn-default search-bar-submit">
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </span>
  </div>
<% end %>

app/views/jobs/index.html.erb
<div class="btn-group pull-left" role="group" aria-label="filters" style="margin: 20px 0px 20px 0px">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      地点
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li>
        <%= link_to("北京", jobs_path(:location => "北京")) %>
      </li>
      <li>
        <%= link_to("上海", jobs_path(:location => "上海")) %>
      </li>
      <li>
        <%= link_to("广州", jobs_path(:location => "广州")) %>
      </li>
      <li>
        <%= link_to("深圳", jobs_path(:location => "深圳")) %>
      </li>
      <li>
        <%= link_to("其他", jobs_path(:location => "其他")) %>
      </li>
    </ul>
  </div>

  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      类别
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li>
        <%= link_to("咖啡", jobs_path(:category => "咖啡")) %>
      </li>
      <li>
        <%= link_to("餐厅", jobs_path(:category => "餐厅")) %>
      </li>
      <li>
        <%= link_to("酒吧", jobs_path(:category => "酒吧")) %>
      </li>
    </ul>
  </div>

  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      全部工作
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li>
        <%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
      </li>
      <li>
        <%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %>
      </li>
      <li>
        <%= link_to("按照发布时间排序", jobs_path) %>
      </li>
    </ul>
  </div>
</div>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <td>职位名称</td>
      <td>薪资范围</td>
      <td>职位类别</td>
      <td>发布公司</td>
      <td>城市</td>
      <td>发布时间</td>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td>
        <%= link_to(job.title, job_path(job)) %>
      </td>
      <td>
        <%= job.wage_lower_bound %> ～ <%= job.wage_upper_bound %>
      </td>
      <td>
        <%= job.category %>
      </td>
      <td>
        <%= job.company %>
      </td>
      <td>
        <%= job.location %>
      </td>
      <td>
        <%= job.created_at %>
      </td>
      <td>
        <% if !current_user %>
          <a href="#" data-toggle="modal" data-target="#signup-modal" class="btn btn-info">注册投简历</a>
        <% end %>

        <div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
          <div class="modal-dialog">
            <div class="loginmodal-container">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h2>注册新用户</h2>

              <div>

                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#personal" aria-controls="personal" role="tab" data-toggle="tab">个人用户</a></li>
                  <li role="presentation"><a href="#business" aria-controls="business" role="tab" data-toggle="tab">企业用户</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane active" id="personal"><%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                    <%= f.error_notification %>
                      <div class="form-inputs">
                        <br />
                        <%= f.input :email, label: "邮箱", required: true, autofocus: true %>
                        <%= f.input :name, label: "用户名", required: true %>
                        <%= f.input :password, label: "密码", required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
                        <%= f.input :password_confirmation, label: "确认密码", required: true %>
                      </div>
                      <div class="form-actions">
                          <%= f.button :submit, "注册" %>
                      </div>
                    <% end %>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="business">
                    <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                    <%= f.error_notification %>
                    <div class="form-inputs">
                      <br />
                      <%= f.input :email, label: "邮箱", required: true, autofocus: true %>
                      <%= f.input :name, label: "公司名称", required: true %>
                      <%= f.input :password, label: "密码", required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
                      <%= f.input :password_confirmation, label: "确认密码", required: true %>
                      <%= f.hidden_field :is_admin, value: "true" %>
                    </div>
                    <div class="form-actions">
                        <%= f.button :submit, "注册" %>
                    </div>
                  <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <% if current_user && !current_user.is_admin %>
          <div class="pull-left">
            <% if current_user && current_user.is_applicant_of?(job) %>
              <%= link_to("已投递", "#", :class => "btn btn-success" ) %>
            <% else %>
              <%= link_to("投简历", new_job_resume_path(job), :class => "btn btn-default" ) %>
            <% end %>
          </div>

          <div class="pull-left">
            <% if current_user && current_user.is_follower_of?(job) %>
              <%= link_to("取消收藏", unfollow_job_path(job), method: :post, :class => "btn btn-info") %>
            <% else %>
              <%= link_to("收藏工作", follow_job_path(job), method: :post, :class => "btn btn-default") %>
            <% end %>
          </div>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="text-center">
  <%= will_paginate @jobs %>
</div>

app/views/jobs/search.html.erb
<div id="search-page" class="container-fluid jobs-show-page">
  <div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
    <br>
    <div class="pull-right">
      <%= link_to(content_tag(:i, " Check All Jobs", class: "fa fa-reply-all"), jobs_path) %> |
      <%= link_to(content_tag(:i, " Back", class: "fa fa-arrow-left"), url_for(:back)) %>
    </div>

    <% if @jobs.blank?%>
      <br>
      <div>
        Opps! No any results matched, please try again.
      </div>
    <% else %>
      <h3>Total find <%= @jobs.count %> jobs</h3>
      <div class="search-result">
        <table class="table table-borderd">
          <% @jobs.each do |job| %>
            <%= link_to(job.title,job_path(job)) %>
            <hr>
          <% end %>
       </table>
      </div>
    <% end %>
  </div>
</div>
<div class="text-center">
  <%= will_paginate @jobs %>
</div>

app/views/jobs/show.html.erb
<div class="row show-title">
  <div class="col-md-8">
    <p> <%= @job.company %>招聘
      <h1 style="margin-top:10px"> <%= @job.title %> </h1>
      <span style="color:#FF5E2E"><%= @job.wage_lower_bound %> ～
      <%= @job.wage_upper_bound %></span> /
      <%= @job.location %> /
      <%= @job.category %>
    </p>
  </div>
  <div class="col-md-4">
    <% if current_user && !current_user.is_admin %>
      <div class="pull-left">
        <% if current_user && current_user.is_follower_of?(@job) %>
          <%= link_to("取消收藏", unfollow_job_path(@job), method: :post, :class => "btn btn-info") %>
        <% else %>
          <%= link_to("收藏工作", follow_job_path(@job), method: :post, :class => "btn btn-default") %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row show-description">
  <h5>职位描述：</h5>
  <%= simple_format(@job.description) %>
</div>