config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :jobs do
    member do
      post :follow
      post :unfollow
    end
    collection do
      get :search
    end
    resources :resumes
  end

  root "welcome#index"

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end

      resources :resumes
    end
  end

  namespace :account do
    resources :jobs
    resources :resumes
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id               :integer          not null, primary key
#  title            :string
#  description      :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  wage_upper_bound :integer
#  wage_lower_bound :integer
#  contact_email    :string
#  is_hidden        :boolean          default("t")
#  user_id          :integer
#  location         :string
#  category         :string
#  company          :string
#

class Job < ApplicationRecord
  validates :title, presence: { message: "请填写职位名称" }
  validates :wage_upper_bound, presence: { message: "请填写薪资上限" }
  validates :wage_lower_bound, presence: { message: "请填写薪资下限" }
  validates :wage_lower_bound, numericality: { greater_than: 0, message: "薪资下限必须大于零" }
  validates :wage_lower_bound, numericality: { less_than: :wage_upper_bound, message: "薪资下限不能高于薪资上限" }
  validates :location, presence: { message: "请选择工作地点" }
  validates :category, presence: { message: "请选择工作种类" }
  validates :contact_email, presence: { message: "请填写联系用邮箱" }
  validates_format_of :contact_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i , message: "请输入正确的邮箱格式"


  scope :published, -> {where(is_hidden: false)}
  scope :recent, -> {order('created_at DESC')}

  has_many :resumes
  belongs_to :user
  has_many :favorites
  has_many :followers, through: :favorites, source: :user
  has_many :applicant, through: :resumes, source: :user
end

app/controllers/account/jobs_controller.rb
class Account::JobsController < ApplicationController
  before_action :authenticate_user!

  def index
    @jobs = case params[:order]
    when 'by_lower_bound'
      current_user.favorited_jobs.order('wage_lower_bound DESC').paginate(:page => params[:page], :per_page => 5)
    when 'by_upper_bound'
      current_user.favorited_jobs.order('wage_upper_bound DESC').paginate(:page => params[:page], :per_page => 5)
    else
      current_user.favorited_jobs.recent.paginate(:page => params[:page], :per_page => 5)
    end
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_is_admin

  layout "admin"

  def index
    @jobs = current_user.jobs.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @job = Job.new
    render :layout => false
  end

  def show
    find_job_and_check_permission
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    @job.company = current_user.name

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    find_job_and_check_permission
  end

  def update
    find_job_and_check_permission
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    find_job_and_check_permission
    @job.destroy
    redirect_to admin_jobs_path, alert: "已删除工作！"
  end

  def publish
    find_job_and_check_permission
    @job.is_hidden = false
    @job.save
    redirect_to :back
  end

  def hide
    find_job_and_check_permission
    @job.is_hidden = true
    @job.save
    redirect_to :back
  end

  private

  def find_job_and_check_permission
    @job = Job.find(params[:id])

    if current_user != @job.user
      redirect_to root_path, alert: "你没有权限！"
    end
  end

  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden, :category, :location, :company)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :follow, :unfollow]
  before_action :validate_search_key, only: [:search]


  def index
    if params[:location].present?
      @location = params[:location]
      @jobs = case params[:order]
      when 'by_lower_bound'
        Job.where(:is_hidden => false, :location => @location).order('wage_lower_bound DESC').paginate(:page => params[:page], :per_page => 10)
      when 'by_upper_bound'
        Job.where(:is_hidden => false, :location => @location).order('wage_upper_bound DESC').paginate(:page => params[:page], :per_page => 10)
      else
        Job.where(:is_hidden => false, :location => @location).recent.paginate(:page => params[:page], :per_page => 10)
      end

    elsif params[:category].present?
      @category = params[:category]
      @jobs = case params[:order]
      when 'by_lower_bound'
        Job.where(:is_hidden => false, :category => @category).order('wage_lower_bound DESC').paginate(:page => params[:page], :per_page => 10)
      when 'by_upper_bound'
        Job.where(:is_hidden => false, :category => @category).order('wage_upper_bound DESC').paginate(:page => params[:page], :per_page => 10)
      else
        Job.where(:is_hidden => false, :category => @category).recent.paginate(:page => params[:page], :per_page => 10)
      end

    else
      @jobs = case params[:order]
      when 'by_lower_bound'
        Job.published.order('wage_lower_bound DESC').paginate(:page => params[:page], :per_page => 10)
      when 'by_upper_bound'
        Job.published.order('wage_upper_bound DESC').paginate(:page => params[:page], :per_page => 10)
      else
        Job.published.recent.paginate(:page => params[:page], :per_page => 10)
      end
    end
  end

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "该工作暂未公开"
      redirect_to root_path
    end
  end

  def follow
    @job = Job.find(params[:id])

    if !current_user.is_follower_of?(@job)
      current_user.follow!(@job)
      flash[:notice] = "已收藏工作"
    end

    redirect_to :back
  end

  def unfollow
    @job = Job.find(params[:id])

    if current_user.is_follower_of?(@job)
      current_user.unfollow!(@job)
      flash[:alert] = "收藏已取消"
    end

    redirect_to :back
  end

  def search
    if @query_string.present?
      search_result = Job.published.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.recent.paginate(:page => params[:page], :per_page => 10 )
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "")
    if params[:q].present?
      @search_criteria =  search_criteria(@query_string)
    end
  end

  def search_criteria(query_string)
    { :title_or_description_or_location_or_category_or_company_cont => query_string }
  end
end

app/helpers/account/jobs_helper.rb
module Account::JobsHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/_form.html.erb
<%= simple_form_for [:admin, @job] do |f| %>

  <%= f.input :title, label: "职位名称" %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :category, label: "工作类别", collection: ["咖啡", "餐厅", "酒吧"] %>
    </div>
    <div class="col-md-6">
      <%= f.input :location, label: "工作地点", collection: ["北京", "上海", "广州", "深圳", "其他"] %>
    </div>
  </div>
  <%= f.input :description, label: "详细描述" %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :wage_lower_bound, label: "薪资下限" %>
    </div>
    <div class="col-md-6">
      <%= f.input :wage_upper_bound, label: "薪资上限" %>
    </div>
  </div>
  <%= f.input :contact_email, label: "联络邮箱" %>
  <%= f.input :is_hidden, label: "暂不公开" %>
  <%= f.submit "保存", disable_with: "发送中...", class: "btn btn-success"%>
  <%= link_to("取消", admin_jobs_path, class:"btn btn-default") %>
<% end %>

app/views/admin/jobs/edit.html.erb
<h1>编辑职缺</h1>

<%= render "form" %>

app/views/admin/jobs/index.html.erb
<div class="pull-right" style="margin-top: 20px">
  <%= link_to("新建职缺", new_admin_job_path, class: %w(btn btn-success), data: { toggle: "modal", target: "#newJobModal"  }) %>
</div>

<!-- Modal -->
<div class="modal fade" id="newJobModal" tabindex="-1" role="dialog" aria-labelledby="newJobModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <!-- <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="newJobModalLabel">Modal title</h4>
      </div> -->
      <!-- <div class="modal-body">
        ...
      </div> -->
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <td>职缺名称</td>
      <td>类别</td>
      <td>收到履历数</td>
      <td>薪资范围</td>
      <td>管理选项</td>
      <td>发布时间</td>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td>
          <%= render_job_status(job) %>
          <%= link_to(job.title, admin_job_path(job)) %>
        </td>
        <td><%= job.category %></td>
        <td><%= link_to(job.resumes.count, admin_job_resumes_path(job)) %></td>
        <td>
          <%= job.wage_lower_bound %>～
          <%= job.wage_upper_bound %>
        </td>
        <td>
          <%= link_to edit_admin_job_path(job), class: "btn btn-xs btn-info" do %><i class="fa fa-pencil"></i><% end %>
          <%= link_to admin_job_path(job), :method => :delete, :class => "btn btn-xs  btn-danger", :data => { :confirm => "真的要删除吗？" } do %><i class="fa fa-trash-o"></i><% end %>
          <% if job.is_hidden %>
            <%= link_to publish_admin_job_path(job) , :method => :post, :class => "btn btn-xs btn-success" do %><i class="fa fa-eye"></i><% end %>
          <% else %>
            <%= link_to hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-warning" do %><i class="fa fa-eye-slash"></i><% end %>
          <% end %>
        </td>
        <td>
          <%= job.created_at %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="text-center">
  <%= will_paginate @jobs %>
</div>

app/views/admin/jobs/new.html.erb
<div class="jobmodal-container">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h1>新建职缺</h1>
  <%= render "form" %>
</div>

app/views/admin/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= @job.company %>
  <%= @job.location %>
  <%= @job.category %>
  <%= @job.wage_lower_bound %>
  <%= @job.wage_upper_bound %>
  <%= simple_format(@job.description) %>
</p>